# Generated by Django 4.1.3 on 2022-11-14 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsops', '0002_alter_passenger_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='passenger',
            table='passenger',
        ),
    ]
