# Generated by Django 4.1.3 on 2022-11-21 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsops', '0003_alter_passenger_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
            ],
            options={
                'db_table': 'personnel',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_max_speed', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'route',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=50)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmsops.address')),
            ],
            options={
                'db_table': 'station',
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'train',
            },
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='passenger_id',
        ),
        migrations.CreateModel(
            name='WorkRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('since', models.DateField()),
                ('personnel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmsops.personnel')),
                ('train_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmsops.train')),
            ],
            options={
                'db_table': 'workRoster',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('date', models.DateField()),
                ('travels_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmsops.train')),
            ],
            options={
                'db_table': 'trip',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('price', models.IntegerField(default=0)),
                ('passenger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmsops.passenger')),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmsops.route')),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_index', models.IntegerField(default=0)),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmsops.station')),
            ],
            options={
                'db_table': 'stop',
            },
        ),
        migrations.CreateModel(
            name='ScheduledOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmsops.route')),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmsops.station')),
            ],
            options={
                'db_table': 'scheduledOn',
            },
        ),
        migrations.AddField(
            model_name='route',
            name='station_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmsops.station'),
        ),
        migrations.CreateModel(
            name='AffiliatedWith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_index', models.IntegerField(default=0)),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmsops.route')),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmsops.station')),
            ],
            options={
                'db_table': 'affiliatedWith',
            },
        ),
        migrations.AddField(
            model_name='passenger',
            name='address_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='dbmsops.address'),
        ),
    ]
