# Generated by Django 4.1.3 on 2022-11-21 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsops', '0004_address_personnel_route_station_train_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliatedwith',
            name='route_id',
        ),
        migrations.RemoveField(
            model_name='affiliatedwith',
            name='station_id',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='address_id',
        ),
        migrations.RemoveField(
            model_name='route',
            name='station_id',
        ),
        migrations.RemoveField(
            model_name='scheduledon',
            name='route_id',
        ),
        migrations.RemoveField(
            model_name='scheduledon',
            name='station_id',
        ),
        migrations.RemoveField(
            model_name='station',
            name='address_id',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='station_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='passenger_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='route_id',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='travels_on',
        ),
        migrations.RemoveField(
            model_name='workroster',
            name='personnel_id',
        ),
        migrations.RemoveField(
            model_name='workroster',
            name='train_id',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='AffiliatedWith',
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
        migrations.DeleteModel(
            name='Personnel',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.DeleteModel(
            name='ScheduledOn',
        ),
        migrations.DeleteModel(
            name='Station',
        ),
        migrations.DeleteModel(
            name='Stop',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='Train',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
        migrations.DeleteModel(
            name='WorkRoster',
        ),
    ]
