# Generated by Django 4.1.3 on 2022-11-24 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsops', '0008_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='address_id',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
