# Generated by Django 4.1.3 on 2022-11-24 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsops', '0009_remove_station_address_id_delete_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengeraddress',
            name='passenger_id',
        ),
        migrations.RemoveField(
            model_name='scheduledon',
            name='station_id',
        ),
        migrations.RemoveField(
            model_name='scheduledon',
            name='trip_id',
        ),
        migrations.RemoveField(
            model_name='stationaddress',
            name='station',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='station_id',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='trip_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='passenger_id',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='travels_on',
        ),
        migrations.RemoveField(
            model_name='workroster',
            name='personnel_id',
        ),
        migrations.RemoveField(
            model_name='workroster',
            name='train_id',
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
        migrations.DeleteModel(
            name='PassengerAddress',
        ),
        migrations.DeleteModel(
            name='Personnel',
        ),
        migrations.DeleteModel(
            name='ScheduledOn',
        ),
        migrations.DeleteModel(
            name='Station',
        ),
        migrations.DeleteModel(
            name='StationAddress',
        ),
        migrations.DeleteModel(
            name='Stop',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='Train',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
        migrations.DeleteModel(
            name='WorkRoster',
        ),
    ]
