# Generated by Django 4.1.3 on 2022-11-24 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dbmsops', '0010_remove_passengeraddress_passenger_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
            ],
            options={
                'db_table': 'passenger',
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
            ],
            options={
                'db_table': 'personnel',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'station',
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('type', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'train',
            },
        ),
        migrations.CreateModel(
            name='StationAddress',
            fields=[
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dbmsops.station')),
                ('street', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('zip', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'stationAddress',
            },
        ),
        migrations.CreateModel(
            name='WorkRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('work_date', models.DateField()),
                ('personnel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmsops.personnel')),
                ('train_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmsops.train')),
            ],
            options={
                'db_table': 'workRoster',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration', models.IntegerField(default=0)),
                ('distance', models.IntegerField(default=0)),
                ('travels_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmsops.train')),
            ],
            options={
                'db_table': 'trip',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('is_valid', models.BooleanField()),
                ('fare', models.FloatField(default=0.0)),
                ('passenger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmsops.passenger')),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmsops.trip')),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_index', models.IntegerField(default=0)),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmsops.station')),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmsops.trip')),
            ],
            options={
                'db_table': 'stop',
            },
        ),
        migrations.CreateModel(
            name='ScheduledOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmsops.station')),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmsops.trip')),
            ],
            options={
                'db_table': 'scheduledOn',
            },
        ),
        migrations.CreateModel(
            name='PassengerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('zip', models.CharField(max_length=10)),
                ('passenger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmsops.passenger')),
            ],
            options={
                'db_table': 'passengerAddress',
            },
        ),
    ]
