# Generated by Django 4.1.3 on 2022-11-25 22:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsops', '0012_station_built_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledon',
            name='date_time',
        ),
        migrations.AddField(
            model_name='scheduledon',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduledon',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stop',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stop',
            name='arrival_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='stop',
            name='departure_time',
            field=models.TimeField(),
        ),
    ]
