# Generated by Django 4.1.3 on 2022-11-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsops', '0013_remove_scheduledon_date_time_scheduledon_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query1Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Query2Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Query3Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('no_of_tickets', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Query4Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100)),
                ('no_of_trains', models.IntegerField()),
            ],
        ),
        migrations.AlterModelTable(
            name='passengeraddress',
            table='passenger_address',
        ),
        migrations.AlterModelTable(
            name='scheduledon',
            table='scheduled_on',
        ),
        migrations.AlterModelTable(
            name='stationaddress',
            table='station_address',
        ),
        migrations.AlterModelTable(
            name='workroster',
            table='work_roster',
        ),
    ]
