# Generated by Django 4.1.3 on 2022-11-26 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsops', '0014_query1model_query2model_query3model_query4model_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Query1Model',
        ),
        migrations.DeleteModel(
            name='Query2Model',
        ),
        migrations.DeleteModel(
            name='Query3Model',
        ),
        migrations.DeleteModel(
            name='Query4Model',
        ),
    ]
